### ISSUE TITLE
持久化和命令行那节编译报错

### ISSUE THREAD

**Issue by jiyilanzhou** [wangweiX/blockchain-java#3]
java -jar blockchain-java-jar-with-dependencies.jar -h 这一行执行没问题。
执行如下命令 java -jar blockchain-java-jar-with-dependencies.jar -add "Send 1.5 BTC to wangwei"
发生如下错误
E:\Android\blockchain-java>java -jar target\blockchain-java-jar-with-dependencies.jar  -print
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
        at one.wangwei.blockchain.store.RocksDBUtils.openDB(RocksDBUtils.java:62)
        at one.wangwei.blockchain.store.RocksDBUtils.<init>(RocksDBUtils.java:53)
        at one.wangwei.blockchain.store.RocksDBUtils.getInstance(RocksDBUtils.java:38)
        at one.wangwei.blockchain.cli.CLI.parse(CLI.java:49)
        at one.wangwei.blockchain.cli.Main.main(Main.java:7)

**Comment by wangweiX** [comment]
Hi,  jiyilanzhou，你好。
使用 BlockchainTest 执行命令 [Send 1.5 BTC to wangwei] 是否正常？
